name: Firebase Deployment

"on":
  push:
    branches:
      - main
      - dev
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build

            ## Install dependencies
      - name: npm install
        run: |
          yarn

      - name: Build & Deploy Dev
        uses: w9jds/firebase-action@master
        if: contains(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/dev'
        with:
          args: deploy --only hosting:dev
       

      - name: Build & Deploy stage
        uses: w9jds/firebase-action@master
        if: contains(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/stage'
        with:
          args: deploy --only hosting:stage
       

        ## Build & Deploy Production
      - name: Build & Deploy Main
        uses: w9jds/firebase-action@master
        if: github.ref == 'refs/heads/main'
        with:
          args: deploy --only hosting:main

      # - uses: FirebaseExtended/action-hosting-deploy@v0
      # # - uses: w9jds/firebase-action@master
      #   with:
      #     repoToken: "${{ secrets.GITHUB_TOKEN }}"
      #     firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }}"
      #     channelId: live
      #     projectId: cicd-96724
