name: Firebase Deployment

"on":
  push:
    branches:
      - main
      - dev
      - stage
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build

      - name: npm install
        run: |
          npm install

      - name: Build & Deploy Dev
        if: contains(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/dev'
        run: |
          npm run build
          npm firebase target:apply hosting dev
          npm firebase deploy --only hosting -P dev --token ${{ secrets.FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      - name: Build & Deploy stage
        if: contains(github.ref, 'refs/heads/feature/') || github.ref == 'refs/heads/stage'
        run: |
          npm run build
          npm firebase target:apply hosting stage
          npm firebase deploy --only hosting -P stage --token ${{ secrets.FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

        ## Build & Deploy Production
      - name: Build & Deploy Main
        if: github.ref == 'refs/heads/main'
        run: |
          npm run build
          npm firebase target:apply hosting main
          npm firebase deploy --only hosting -P main --token ${{ secrets.FIREBASE_TOKEN }} --message "$CI_FIREBASE_MESSAGE"

      # - uses: FirebaseExtended/action-hosting-deploy@v0
      - uses: w9jds/firebase-action@master
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }}"
          channelId: live
          projectId: cicd-96724
